// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCMwD4S9akURRZ_u7iuhgSGsyvUWh941TQ',
    appId: '1:803393145214:web:fb57201234e651b91d0b2f',
    messagingSenderId: '803393145214',
    projectId: 'smarttask-9c578',
    authDomain: 'smarttask-9c578.firebaseapp.com',
    storageBucket: 'smarttask-9c578.firebasestorage.app',
    measurementId: 'G-77NFX5S6W4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCWJe1bJ3fz5jHhaELkmcmG8rrr1PWu7hw',
    appId: '1:803393145214:android:4a3e88127f6444d41d0b2f',
    messagingSenderId: '803393145214',
    projectId: 'smarttask-9c578',
    storageBucket: 'smarttask-9c578.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCoFtGIA7m_tSf7C7pPl4k5b6YI6A2g8pA',
    appId: '1:803393145214:ios:d1aed486ce1134711d0b2f',
    messagingSenderId: '803393145214',
    projectId: 'smarttask-9c578',
    storageBucket: 'smarttask-9c578.firebasestorage.app',
    iosBundleId: 'com.inkomoko.smarttask',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCoFtGIA7m_tSf7C7pPl4k5b6YI6A2g8pA',
    appId: '1:803393145214:ios:6e9627e9f3fd90971d0b2f',
    messagingSenderId: '803393145214',
    projectId: 'smarttask-9c578',
    storageBucket: 'smarttask-9c578.firebasestorage.app',
    iosBundleId: 'com.example.smarttask',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCMwD4S9akURRZ_u7iuhgSGsyvUWh941TQ',
    appId: '1:803393145214:web:0fbef6f45cb97b641d0b2f',
    messagingSenderId: '803393145214',
    projectId: 'smarttask-9c578',
    authDomain: 'smarttask-9c578.firebaseapp.com',
    storageBucket: 'smarttask-9c578.firebasestorage.app',
    measurementId: 'G-EV1TYNWKB8',
  );
}
